landingApp/urls.py
from django.urls import path
from . import views
from .views import *
from django.conf.urls import url

app_name = 'landingApp'

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.DeleteStatus.as_view(), name='delete'),
    path('tambah_status/',tambah_status, name='tambah_status'),
]

projectStory6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingApp.urls')),
]

landingApp/models.py
from django.db import models

class Status(models.Model):
    status = models.CharField(max_length=300)
    waktu = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

landingApp/forms.py
from django import forms
from .models import Status


class PostForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'

landingApp/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Status
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

class DeleteStatus(DeleteView):
        model = Status
        success_url = reverse_lazy('landingApp:landingPage')

def landingPage(request):

    context = {
        'post_form' : PostForm(),
        'posting': Status.objects.all() 
    }
    return render(request, 'landingPage.html',context)

def tambah_status(request):
    if PostForm(request.POST).is_valid():
        status_baru = Status.objects.create(status=request.POST['status'])
    return redirect('landingApp:landingPage')

    

landingApp/templates/landingPage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Story 6 Wildan</title>
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
        
    </style>
</head>
<body style= "background-color: #69bcd1;" >
    <div class="container">
        <form action="{% url 'landingApp:tambah_status' %}" method="POST"style="margin: 5vw 15vw">
            <h1>Halo, Apa Kabar?</h1>
            {% csrf_token %}
            <table>
                {{post_form.as_table}}
            </table>
            <button type="submit">Post</button>

        </form>
        
        {% for a in posting %} 
        <p style= " border: 1px solid black; border-radius: 10px; padding: 5px 25px; width: 50vw; max-width: 50vw">{{a.status}}</p>
        <p>{{a.waktu}}</p>
        <form action="{% url 'landingApp:delete' a.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="a_id" value="{{ a.id }}"/>
            <button type="" class="btn-sm col-2" style= "width: 10vw;" >Hapus</button> 
        </form>
        <br>
        
        {% endfor %}
    </div>
</body>


</html>